name: CI Api Gem Hunts

on:
  push:
    branches:
      - gemhunts

jobs:
  dist:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: zip -r deploy.zip build tsconfig.json yarn.lock package.json

      - name: Copy to Gem Hunts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GEMHUNTS_IP }}
          username: ${{ secrets.GEMHUNTS_USER }}
          password: ${{ secrets.GEMHUNTS_PASSWORD }}
          source: "deploy.zip"
          target: "~/code/mensageria"

      - name: Multiple Command on Gem Hunts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GEMHUNTS_IP }}
          username: ${{ secrets.GEMHUNTS_USER }}
          password: ${{ secrets.GEMHUNTS_PASSWORD }}
          script: |
            cd ~/code/mensageria
            # pm2 stop mensageria
            unzip -o deploy.zip
            yarn install --production
            rm -rf deploy.zip
            # pm2 start mensageria
